### PR TITLE
Update to latest PS2SDK.

### PR DESCRIPTION
**Pull request by Wolf3s**
## Pull Request checklist

Note: these are not necessarily requirements

- [ ] I reformatted the code with clang-format
- [ ] I checked to make sure my submission worked
- [ ] I am the author of submission or have permission from the original author
- [ ] Requires update of the PS2SDK or other dependencies
- [ ] Others (please specify below)

### CODE REVIEW

**Comment by AKuHAK** [comment]
better switch to the container: `ghcr.io/ps2homebrew/ps2homebrew:latest`

**Comment by Wolf3s** [comment]
> better switch to the container: `ghcr.io/ps2homebrew/ps2homebrew:latest`

Will do.

**Comment by Wolf3s** [comment]
> better switch to the container: `ghcr.io/ps2homebrew/ps2homebrew:latest`

Done however there´s no latest tag only main.

**Comment by Wolf3s** [comment]
> > better switch to the container: `ghcr.io/ps2homebrew/ps2homebrew:latest`
> 
> Done however there´s no latest tag only main.

Btw thx, I will add this to ps2sdk-ports.

**Comment by AKuHAK** [comment]
> Btw thx, I will add this to ps2sdk-ports.

yes, it has many dpendencies and auto-updates when main image is updated

**Comment by Wolf3s** [comment]
> > Btw thx, I will add this to ps2sdk-ports.
> 
> yes, it has many dpendencies and auto-updates when main image is updated

I opened a pr there that reduces some downloadable dependencies.

**Pull request merged**
